// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214220326_Update_MedicalRecord_Entity")]
    partial class Update_MedicalRecord_Entity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.DepartmentTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AdmissionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TransferType")
                        .HasColumnType("int");

                    b.Property<string>("TreatmentDays")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("DepartmentTransfers");
                });

            modelBuilder.Entity("Domain.Entities.Ethnicity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Ethnicities");
                });

            modelBuilder.Entity("Domain.Entities.Hematology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbnormalCells")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<float?>("Basophil")
                        .HasColumnType("real");

                    b.Property<int?>("BleedingTime")
                        .HasColumnType("int");

                    b.Property<int?>("BloodTypeAbo")
                        .HasColumnType("int");

                    b.Property<int?>("BloodTypeRh")
                        .HasColumnType("int");

                    b.Property<int?>("ClottingTime")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Eosinophil")
                        .HasColumnType("real");

                    b.Property<float?>("Esr1h")
                        .HasColumnType("real");

                    b.Property<float?>("Esr2h")
                        .HasColumnType("real");

                    b.Property<float?>("Hematocrit")
                        .HasColumnType("real");

                    b.Property<float?>("Hemoglobin")
                        .HasColumnType("real");

                    b.Property<bool>("IsEmergency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float?>("Lymphocyte")
                        .HasColumnType("real");

                    b.Property<string>("MalariaParasite")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float?>("Mch")
                        .HasColumnType("real");

                    b.Property<float?>("Mchc")
                        .HasColumnType("real");

                    b.Property<float?>("Mcv")
                        .HasColumnType("real");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<float?>("Monocyte")
                        .HasColumnType("real");

                    b.Property<float?>("Neutrophil")
                        .HasColumnType("real");

                    b.Property<string>("NucleatedRedBloodCell")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PerformedById")
                        .HasColumnType("int");

                    b.Property<float?>("PlateletCount")
                        .HasColumnType("real");

                    b.Property<float?>("RedBloodCellCount")
                        .HasColumnType("real");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int");

                    b.Property<float?>("ReticulocyteCount")
                        .HasColumnType("real");

                    b.Property<float?>("WhiteBloodCellCount")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("PerformedById");

                    b.HasIndex("RequestedById");

                    b.ToTable("Hematologies");
                });

            modelBuilder.Entity("Domain.Entities.MedicalAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("MedicalAttachments");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AddressJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("1");

                    b.Property<string>("AdmissionDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdmissionTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AdmissionType")
                        .HasColumnType("int");

                    b.Property<string>("BedCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DeathCause")
                        .HasColumnType("int");

                    b.Property<int?>("DeathMainCode")
                        .HasColumnType("int");

                    b.Property<string>("DeathMainReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeathTimeGroup")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisAutopsy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiagnosisCode")
                        .HasColumnType("int");

                    b.Property<string>("DischargeMainCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DischargeMainDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DischargeSubCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DischargeSubDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DischargeTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DischargeType")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictCode")
                        .HasColumnType("int");

                    b.Property<string>("DistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("HasAccident")
                        .HasColumnType("bit");

                    b.Property<bool>("HasAutopsy")
                        .HasColumnType("bit");

                    b.Property<bool>("HasComplication")
                        .HasColumnType("bit");

                    b.Property<bool>("HasProcedure")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSurgery")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HealthInsuranceExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HospitalTransferDestination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HospitalTransferType")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PathologyResult")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentCategory")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceCode")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordType")
                        .HasColumnType("int");

                    b.Property<string>("ReferralCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferralSource")
                        .HasColumnType("int");

                    b.Property<string>("RelativeInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TotalTreatmentDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TreatmentResult")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecordDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AdmissionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BodyWeight")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DiagnosisDifferential")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisMain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisSub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamCardio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamEndocrineOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamGastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamGeneral")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExamMaxillofacial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamMusculoskeletal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamNeurological")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamOphthalmology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamRenalUrology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamRespiratory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyHistory")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PathologicalProcess")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PersonalHistory")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PulseRate")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("RespiratoryRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperature")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("MedicalRecordDetails");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecordRiskFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DurationMonth")
                        .HasColumnType("int");

                    b.Property<bool?>("IsPossible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MedicalRecordDetailId")
                        .HasColumnType("int");

                    b.Property<int?>("Signed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordDetailId");

                    b.ToTable("MedicalRecordRiskFactors");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("EthnicityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(56);

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("HealthInsuranceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EthnicityId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.XRay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorAdvice")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<int?>("PerformedById")
                        .HasColumnType("int");

                    b.Property<string>("RequestDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int");

                    b.Property<string>("ResultDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("PerformedById");

                    b.HasIndex("RequestedById");

                    b.ToTable("XRays");
                });

            modelBuilder.Entity("Domain.Entities.DepartmentTransfer", b =>
                {
                    b.HasOne("Domain.Entities.MedicalRecord", "MedicalRecord")
                        .WithMany("DepartmentTransfers")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Domain.Entities.Hematology", b =>
                {
                    b.HasOne("Domain.Entities.MedicalRecord", "MedicalRecord")
                        .WithMany("Hematologies")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalRecord");

                    b.Navigation("PerformedBy");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("Domain.Entities.MedicalAttachment", b =>
                {
                    b.HasOne("Domain.Entities.MedicalRecord", "MedicalRecord")
                        .WithMany("Attachments")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecord", b =>
                {
                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecordDetail", b =>
                {
                    b.HasOne("Domain.Entities.MedicalRecord", "MedicalRecord")
                        .WithOne("Detail")
                        .HasForeignKey("Domain.Entities.MedicalRecordDetail", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecordRiskFactor", b =>
                {
                    b.HasOne("Domain.Entities.MedicalRecordDetail", "MedicalRecordDetail")
                        .WithMany("RiskFactors")
                        .HasForeignKey("MedicalRecordDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecordDetail");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Ethnicity", "Ethnicity")
                        .WithMany()
                        .HasForeignKey("EthnicityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Ethnicity");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.XRay", b =>
                {
                    b.HasOne("Domain.Entities.MedicalRecord", "MedicalRecord")
                        .WithMany("XRays")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalRecord");

                    b.Navigation("PerformedBy");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecord", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("DepartmentTransfers");

                    b.Navigation("Detail");

                    b.Navigation("Hematologies");

                    b.Navigation("XRays");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecordDetail", b =>
                {
                    b.Navigation("RiskFactors");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
