// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425193728_UpdateXraySchedule")]
    partial class UpdateXraySchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HeadUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("HeadUserId")
                        .IsUnique()
                        .HasFilter("[HeadUserId] IS NOT NULL");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Domain.Entities.DepartmentTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AdmissionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TransferType")
                        .HasColumnType("int");

                    b.Property<string>("TreatmentDays")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("DepartmentTransfers");
                });

            modelBuilder.Entity("Domain.Entities.Ethnicity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Ethnicities");
                });

            modelBuilder.Entity("Domain.Entities.Hematology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbnormalCells")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<float?>("Basophil")
                        .HasColumnType("real");

                    b.Property<int?>("BleedingTime")
                        .HasColumnType("int");

                    b.Property<int?>("BloodTypeAbo")
                        .HasColumnType("int");

                    b.Property<int?>("BloodTypeRh")
                        .HasColumnType("int");

                    b.Property<int?>("ClottingTime")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CompletedAt")
                        .HasColumnType("date");

                    b.Property<float?>("Eosinophil")
                        .HasColumnType("real");

                    b.Property<float?>("Esr1h")
                        .HasColumnType("real");

                    b.Property<float?>("Esr2h")
                        .HasColumnType("real");

                    b.Property<float?>("Hematocrit")
                        .HasColumnType("real");

                    b.Property<float?>("Hemoglobin")
                        .HasColumnType("real");

                    b.Property<float?>("Lymphocyte")
                        .HasColumnType("real");

                    b.Property<string>("MalariaParasite")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float?>("Mch")
                        .HasColumnType("real");

                    b.Property<float?>("Mchc")
                        .HasColumnType("real");

                    b.Property<float?>("Mcv")
                        .HasColumnType("real");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<float?>("Monocyte")
                        .HasColumnType("real");

                    b.Property<float?>("Neutrophil")
                        .HasColumnType("real");

                    b.Property<string>("NucleatedRedBloodCell")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PerformedById")
                        .HasColumnType("int");

                    b.Property<float?>("PlateletCount")
                        .HasColumnType("real");

                    b.Property<float?>("RedBloodCellCount")
                        .HasColumnType("real");

                    b.Property<string>("RequestDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("RequestedAt")
                        .HasColumnType("date");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int");

                    b.Property<float?>("ReticulocyteCount")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float?>("WhiteBloodCellCount")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("PerformedById");

                    b.HasIndex("RequestedById");

                    b.ToTable("Hematologies", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HematologyStatusLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("HematologyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HematologyId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("HematologyId", "CreatedAt");

                    b.ToTable("HematologyStatusLogs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MedicalAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("MedicalAttachments");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AddressJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("1");

                    b.Property<string>("AdmissionDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdmissionTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AdmissionType")
                        .HasColumnType("int");

                    b.Property<string>("BedCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DeathCause")
                        .HasColumnType("int");

                    b.Property<int?>("DeathMainCode")
                        .HasColumnType("int");

                    b.Property<string>("DeathMainReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeathReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeathTimeGroup")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisAutopsy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiagnosisCode")
                        .HasColumnType("int");

                    b.Property<string>("DischargeMainCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DischargeMainDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DischargeSubCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DischargeSubDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DischargeTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DischargeType")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictCode")
                        .HasColumnType("int");

                    b.Property<string>("DistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("HasAccident")
                        .HasColumnType("bit");

                    b.Property<bool>("HasAutopsy")
                        .HasColumnType("bit");

                    b.Property<bool>("HasComplication")
                        .HasColumnType("bit");

                    b.Property<bool>("HasProcedure")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSurgery")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HealthInsuranceExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HospitalTransferDestination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HospitalTransferType")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PathologyResult")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentCategory")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceCode")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordType")
                        .HasColumnType("int");

                    b.Property<string>("ReferralCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferralSource")
                        .HasColumnType("int");

                    b.Property<string>("RelativeInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TotalTreatmentDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TreatmentResult")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecordDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AdmissionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BodyWeight")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DiagnosisDifferential")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisMain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisSub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamCardio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamEndocrineOthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamGastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamGeneral")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExamMaxillofacial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamMusculoskeletal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamNeurological")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamOphthalmology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamRenalUrology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamRespiratory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyHistory")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("IllnessDay")
                        .HasColumnType("int");

                    b.Property<string>("MedicalSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathologicalProcess")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PersonalHistory")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Prognosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PulseRate")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("RequiredClinicalTests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespiratoryRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperature")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TreatmentPlan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedicalRecordDetails");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecordRiskFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DurationMonth")
                        .HasColumnType("int");

                    b.Property<bool?>("IsPossible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MedicalRecordDetailId")
                        .HasColumnType("int");

                    b.Property<int?>("Signed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordDetailId");

                    b.ToTable("MedicalRecordRiskFactors");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AppTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("EthnicityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(56);

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("HealthInsuranceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EthnicityId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailVerify")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Id")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEmailSend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("IsEmailSend", "NotificationId");

                    b.HasIndex("UserId", "NotificationId")
                        .IsUnique();

                    b.HasIndex("UserId", "IsRead", "NotificationId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("Domain.Entities.XRay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BedNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CompletedAt")
                        .HasColumnType("date");

                    b.Property<string>("DepartmentOfHealth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorAdvice")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FormNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<int?>("PerformedById")
                        .HasColumnType("int");

                    b.Property<string>("RequestDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("RequestedAt")
                        .HasColumnType("date");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int");

                    b.Property<string>("ResultDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("PerformedById");

                    b.HasIndex("RequestedById");

                    b.ToTable("XRays", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.XRayStatusLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<int>("XRayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("XRayId");

                    b.HasIndex("XRayId", "CreatedAt");

                    b.ToTable("XRayStatusLogs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.HasOne("Domain.Entities.User", "HeadUser")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Department", "HeadUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HeadUser");
                });

            modelBuilder.Entity("Domain.Entities.DepartmentTransfer", b =>
                {
                    b.HasOne("Domain.Entities.MedicalRecord", "MedicalRecord")
                        .WithMany("DepartmentTransfers")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Domain.Entities.Hematology", b =>
                {
                    b.HasOne("Domain.Entities.MedicalRecord", "MedicalRecord")
                        .WithMany("Hematologies")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalRecord");

                    b.Navigation("PerformedBy");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("Domain.Entities.HematologyStatusLog", b =>
                {
                    b.HasOne("Domain.Entities.Hematology", "Hematology")
                        .WithMany("HematologyStatusLogs")
                        .HasForeignKey("HematologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hematology");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Domain.Entities.MedicalAttachment", b =>
                {
                    b.HasOne("Domain.Entities.MedicalRecord", "MedicalRecord")
                        .WithMany("Attachments")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecord", b =>
                {
                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecordDetail", b =>
                {
                    b.HasOne("Domain.Entities.MedicalRecord", "MedicalRecord")
                        .WithOne("Detail")
                        .HasForeignKey("Domain.Entities.MedicalRecordDetail", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecordRiskFactor", b =>
                {
                    b.HasOne("Domain.Entities.MedicalRecordDetail", "MedicalRecordDetail")
                        .WithMany("RiskFactors")
                        .HasForeignKey("MedicalRecordDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecordDetail");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Ethnicity", "Ethnicity")
                        .WithMany()
                        .HasForeignKey("EthnicityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Ethnicity");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.UserNotification", b =>
                {
                    b.HasOne("Domain.Entities.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.XRay", b =>
                {
                    b.HasOne("Domain.Entities.MedicalRecord", "MedicalRecord")
                        .WithMany("XRays")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalRecord");

                    b.Navigation("PerformedBy");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("Domain.Entities.XRayStatusLog", b =>
                {
                    b.HasOne("Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.XRay", "XRay")
                        .WithMany("XRayStatusLogs")
                        .HasForeignKey("XRayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpdatedBy");

                    b.Navigation("XRay");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Hematology", b =>
                {
                    b.Navigation("HematologyStatusLogs");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecord", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("DepartmentTransfers");

                    b.Navigation("Detail");

                    b.Navigation("Hematologies");

                    b.Navigation("XRays");
                });

            modelBuilder.Entity("Domain.Entities.MedicalRecordDetail", b =>
                {
                    b.Navigation("RiskFactors");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("Domain.Entities.Patient", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("Domain.Entities.XRay", b =>
                {
                    b.Navigation("XRayStatusLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
